### Variable
@baseUrl = http://localhost:4741/schools/

### Index
{{baseUrl}}

### Select
{{baseUrl}}/1

### Create
POST {{baseUrl}}
content-type: application/json

{
  "school": {
    "name": "asdf"
  }
}









